root = "."
tmp_dir = "__temp"

[build]
cmd = "go build -o ./__temp/main ./cmd/api/main.go"
bin = "./__temp/main"
include_ext = ["go"]
exclude_dir = ["assets", "__temp"]

[screen]
clear_on_rebuild = true