services:
  postgresql:
    container_name: go-boilerplate-postgres
    image: bitnami/postgresql:latest
    env_file: ".env"
    environment:
      POSTGRESQL_DATABASE: ${DB_NAME}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - go-boilerplate-volumes:/bitnami/postgresql
    networks:
      - go-boilerplate-network

  cache:
    container_name: go-boilerplate-redis
    image: redis:7.2-alpine
    ports:
      - 6379:6379
    networks:
      - go-boilerplate-network

  air:
    container_name: go-boilerplate-air
    image: cosmtrek/air:latest
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      DB_HOST: postgresql
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GOTOOLCHAIN: auto
    volumes:
      - .:/app
    networks:
      - go-boilerplate-network
    depends_on:
      - postgresql

  prometheus:
    image: prom/prometheus
    container_name: go-boilerplate-prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - go-boilerplate-network

  grafana:
    image: grafana/grafana
    container_name: go-boilerplate-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - go-boilerplate-network

volumes:
  go-boilerplate-volumes:
  prometheus-data:


networks:
  go-boilerplate-network:
    driver: bridge
